using System.Collections.Generic;
using UnityEngine;
using Lattirune.Core;

namespace Lattirune.Runes
{
    /// <summary>
    /// Represents a discrete, deterministic beam branch path on the LatticeGrid.
    /// Tracks hierarchical parent/child relationships generated by Prism Rune refractions.
    /// </summary>
    public class ConduitBeamPath
    {
        public string BeamId { get; private set; }
        public string SourceRuneId { get; private set; }
        public ElementType Element { get; private set; }
        public Vector2Int Origin { get; private set; }
        public ConduitDirection Direction { get; private set; }
        public int RequestedRange { get; private set; }
        public IReadOnlyList<Vector2Int> TraversedCells { get; private set; }
        public ConduitTerminationReason TerminationReason { get; private set; }
        public Vector2Int? TargetCell { get; private set; }
        public string ParentBeamId { get; private set; }
        public int Depth { get; private set; }

        public bool IsSplitBranch => !string.IsNullOrEmpty(ParentBeamId);
        public int TraversalLength => TraversedCells != null ? TraversedCells.Count : 0;

        public ConduitBeamPath(
            string beamId,
            string sourceRuneId,
            ElementType element,
            Vector2Int origin,
            ConduitDirection direction,
            int requestedRange,
            List<Vector2Int> traversedCells,
            ConduitTerminationReason terminationReason,
            Vector2Int? targetCell = null,
            string parentBeamId = null,
            int depth = 0)
        {
            BeamId = beamId;
            SourceRuneId = sourceRuneId;
            Element = element;
            Origin = origin;
            Direction = direction;
            RequestedRange = requestedRange;
            TraversedCells = traversedCells ?? new List<Vector2Int>();
            TerminationReason = terminationReason;
            TargetCell = targetCell;
            ParentBeamId = parentBeamId;
            Depth = depth;
        }

        public RuneConduitResult ToConduitResult()
        {
            return new RuneConduitResult(
                Origin, 
                Direction, 
                RequestedRange, 
                new List<Vector2Int>(TraversedCells), 
                TerminationReason, 
                TargetCell
            );
        }
    }
}
