using System;
using System.Collections.Generic;
using UnityEngine;
using Lattirune.Core;
using Lattirune.Grid;

namespace Lattirune.Runes
{
    /// <summary>
    /// Deterministic 2D grid raycasting engine for directional Rune Conduits and Prism refractions.
    /// Traverses the 5x5 LatticeGrid coordinates using discrete integer stepping (zero physics queries).
    /// </summary>
    public static class RuneConduitEngine
    {
        /// <summary>
        /// Maps a cardinal ConduitDirection enum to a discrete 2D integer step vector.
        /// </summary>
        public static Vector2Int GetDirectionVector(ConduitDirection direction)
        {
            switch (direction)
            {
                case ConduitDirection.North: return new Vector2Int(0, 1);
                case ConduitDirection.South: return new Vector2Int(0, -1);
                case ConduitDirection.East:  return new Vector2Int(1, 0);
                case ConduitDirection.West:  return new Vector2Int(-1, 0);
                default:                     return Vector2Int.zero;
            }
        }

        /// <summary>
        /// Calculates the discrete path of a single directional rune conduit across the LatticeGrid.
        /// </summary>
        public static RuneConduitResult CalculateConduit(
            LatticeGrid grid,
            Vector2Int origin,
            ConduitDirection direction,
            int range = LatticeGrid.WIDTH,
            Func<Vector2Int, bool> isTargetPredicate = null,
            bool stopOnTarget = true,
            bool stopOnOccupied = false)
        {
            if (grid == null)
            {
                return RuneConduitResult.CreateEmpty(origin, direction, ConduitTerminationReason.None);
            }

            if (!grid.IsValidCoordinate(origin))
            {
                return RuneConduitResult.CreateEmpty(origin, direction, ConduitTerminationReason.InvalidOrigin);
            }

            Vector2Int stepVector = GetDirectionVector(direction);
            if (stepVector == Vector2Int.zero)
            {
                return RuneConduitResult.CreateEmpty(origin, direction, ConduitTerminationReason.UnsupportedDirection);
            }

            int clampedRange = Mathf.Clamp(range, 1, LatticeGrid.WIDTH);
            List<Vector2Int> traversed = new List<Vector2Int>(clampedRange);
            ConduitTerminationReason terminationReason = ConduitTerminationReason.RangeReached;
            Vector2Int? foundTarget = null;

            for (int step = 1; step <= clampedRange; step++)
            {
                int targetX = origin.x + (stepVector.x * step);
                int targetY = origin.y + (stepVector.y * step);
                Vector2Int currentCoord = new Vector2Int(targetX, targetY);

                // 1. Check Grid Boundary
                if (!grid.IsValidCoordinate(targetX, targetY))
                {
                    terminationReason = ConduitTerminationReason.GridBoundary;
                    break;
                }

                GridCell cell = grid.GetCell(targetX, targetY);

                // 2. Check Locked Cell
                if (cell != null && cell.IsLocked())
                {
                    terminationReason = ConduitTerminationReason.LockedCell;
                    break;
                }

                // 3. Record Traversed Cell
                traversed.Add(currentCoord);

                // 4. Target Detection
                if (isTargetPredicate != null && isTargetPredicate(currentCoord))
                {
                    foundTarget = currentCoord;
                    if (stopOnTarget)
                    {
                        terminationReason = ConduitTerminationReason.TargetFound;
                        break;
                    }
                }

                // 5. Occupied Insulator Check
                if (stopOnOccupied && cell != null && cell.IsOccupied())
                {
                    terminationReason = ConduitTerminationReason.BlockedByOccupant;
                    break;
                }
            }

            return new RuneConduitResult(origin, direction, clampedRange, traversed, terminationReason, foundTarget);
        }

        /// <summary>
        /// Calculates a rune conduit and any refracted child beam branches generated by intersecting Prism runes.
        /// Includes loop protection to prevent circular infinite recursion.
        /// </summary>
        public static List<ConduitBeamPath> CalculateConduitWithRefraction(
            LatticeGrid grid,
            RuneData rune,
            Vector2Int origin,
            ConduitDirection direction,
            int range = LatticeGrid.WIDTH,
            Func<Vector2Int, (bool isPrism, PrismRuneDataSO data)> getPrismAtCell = null,
            Func<Vector2Int, bool> isTargetPredicate = null,
            bool stopOnTarget = true,
            bool stopOnOccupied = false,
            int maxDepth = 3)
        {
            List<ConduitBeamPath> allPaths = new List<ConduitBeamPath>();
            if (grid == null || rune == null || !grid.IsValidCoordinate(origin)) return allPaths;

            HashSet<(Vector2Int pos, ConduitDirection dir)> visitedPrisms = new HashSet<(Vector2Int, ConduitDirection)>();

            void TraceBeam(
                string beamId,
                string parentBeamId,
                Vector2Int beamOrigin,
                ConduitDirection beamDir,
                int beamRange,
                int currentDepth)
            {
                if (currentDepth > maxDepth || beamRange <= 0) return;

                Vector2Int stepVector = GetDirectionVector(beamDir);
                if (stepVector == Vector2Int.zero) return;

                List<Vector2Int> traversed = new List<Vector2Int>();
                ConduitTerminationReason reason = ConduitTerminationReason.RangeReached;
                Vector2Int? foundTarget = null;

                Vector2Int? hitPrismPos = null;
                PrismRuneDataSO hitPrismData = null;
                int stepsTaken = 0;

                for (int step = 1; step <= beamRange; step++)
                {
                    int tx = beamOrigin.x + (stepVector.x * step);
                    int ty = beamOrigin.y + (stepVector.y * step);
                    Vector2Int coord = new Vector2Int(tx, ty);

                    if (!grid.IsValidCoordinate(tx, ty))
                    {
                        reason = ConduitTerminationReason.GridBoundary;
                        break;
                    }

                    GridCell cell = grid.GetCell(tx, ty);
                    if (cell != null && cell.IsLocked())
                    {
                        reason = ConduitTerminationReason.LockedCell;
                        break;
                    }

                    traversed.Add(coord);
                    stepsTaken = step;

                    // Prism Refraction Detection
                    if (getPrismAtCell != null)
                    {
                        var (isPrism, pData) = getPrismAtCell(coord);
                        if (isPrism && pData != null)
                        {
                            hitPrismPos = coord;
                            hitPrismData = pData;
                            reason = ConduitTerminationReason.TargetFound;
                            break; // Ray terminates at prism and splits into branches
                        }
                    }

                    // Target Detection
                    if (isTargetPredicate != null && isTargetPredicate(coord))
                    {
                        foundTarget = coord;
                        if (stopOnTarget)
                        {
                            reason = ConduitTerminationReason.TargetFound;
                            break;
                        }
                    }

                    // Occupant check
                    if (stopOnOccupied && cell != null && cell.IsOccupied())
                    {
                        reason = ConduitTerminationReason.BlockedByOccupant;
                        break;
                    }
                }

                ConduitBeamPath path = new ConduitBeamPath(
                    beamId: beamId,
                    sourceRuneId: rune.RuneId,
                    element: rune.Element,
                    origin: beamOrigin,
                    direction: beamDir,
                    requestedRange: beamRange,
                    traversedCells: traversed,
                    terminationReason: reason,
                    targetCell: foundTarget,
                    parentBeamId: parentBeamId,
                    depth: currentDepth
                );
                allPaths.Add(path);

                // If a prism was hit, split into refracted child branches
                if (hitPrismPos.HasValue && hitPrismData != null)
                {
                    var prismKey = (hitPrismPos.Value, beamDir);
                    if (!visitedPrisms.Contains(prismKey))
                    {
                        visitedPrisms.Add(prismKey);

                        int remainingRange = beamRange - stepsTaken;
                        if (remainingRange > 0)
                        {
                            var (branchDirA, branchDirB) = hitPrismData.GetSplitDirections(beamDir);

                            // Branch A
                            string branchIdA = $"{beamId}_refract_{branchDirA}";
                            TraceBeam(branchIdA, beamId, hitPrismPos.Value, branchDirA, remainingRange, currentDepth + 1);

                            // Branch B
                            string branchIdB = $"{beamId}_refract_{branchDirB}";
                            TraceBeam(branchIdB, beamId, hitPrismPos.Value, branchDirB, remainingRange, currentDepth + 1);
                        }
                    }
                }
            }

            string rootId = $"beam_{rune.RuneId}_{origin.x}_{origin.y}";
            TraceBeam(rootId, null, origin, direction, Mathf.Clamp(range, 1, LatticeGrid.WIDTH), 0);

            return allPaths;
        }

        /// <summary>
        /// Calculates multiple independent rune conduits across the grid in a single pass.
        /// </summary>
        public static List<RuneConduitResult> CalculateMultipleConduits(
            LatticeGrid grid,
            IEnumerable<(Vector2Int origin, ConduitDirection dir, int range)> runeSpecifications,
            Func<Vector2Int, bool> isTargetPredicate = null)
        {
            List<RuneConduitResult> results = new List<RuneConduitResult>();
            if (runeSpecifications == null || grid == null) return results;

            foreach (var (origin, dir, range) in runeSpecifications)
            {
                RuneConduitResult result = CalculateConduit(grid, origin, dir, range, isTargetPredicate);
                results.Add(result);
            }

            return results;
        }
    }
}
